name: Update Total Stars

on:
  schedule:
    - cron: '0 */6 * * *'  # every 6 hours
  workflow_dispatch:

jobs:
  update-stars:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Count stars and update README
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');

            const pinnedRepos = [
              { owner: 'wespreadjam', repo: 'jam-nodes' },
              { owner: 'jia-seed', repo: 'asillios-limiter' },
              { owner: 'wespreadjam', repo: 'jam-discord-bot' },
              { owner: 'jia-seed', repo: 'backend-dev-notes' },
              { owner: 'NextTechOKE', repo: 'Hologlass' },
              { owner: 'jia-seed', repo: 'DIATOS-intel-ai' },
            ];

            let totalStars = 0;

            for (const { owner, repo } of pinnedRepos) {
              try {
                const { data } = await github.rest.repos.get({ owner, repo });
                totalStars += data.stargazers_count;
                console.log(`${owner}/${repo}: ${data.stargazers_count} stars`);
              } catch (e) {
                console.log(`failed to fetch ${owner}/${repo}: ${e.message}`);
              }
            }

            console.log(`total stars: ${totalStars}`);

            let readme = fs.readFileSync('README.md', 'utf8');

            readme = readme.replace(
              /!\[Total Stars\]\(https:\/\/img\.shields\.io\/badge\/total__stars-\d+-yellow\?style=for-the-badge&logo=github\)/,
              `![Total Stars](https://img.shields.io/badge/total__stars-${totalStars}-yellow?style=for-the-badge&logo=github)`
            );

            fs.writeFileSync('README.md', readme);

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git diff --quiet || (git add README.md && git commit -m "update total stars count" && git push)
